### ISSUE TITLE
Error: Cannot `process` without `Compiler`

### ISSUE THREAD

**Issue by nanoia** [pustovitDmytro/remark-telegraph#27]
**Issue Description**

Thanks for the package. When I test with the example code, the program throws an exception at `unified().process(markdown)`, if i change the `unified().process()` to `unified().parse()`, then the method will not return the correct node json that can be accepted by the telegraph api.
```
Error: Cannot `process` without `Compiler`
    at assertCompiler (C:\Users\gut\source\study\mydemo\node_modules\unified\index.js:431:11)
    at Function.process (C:\Users\gut\source\study\mydemo\node_modules\unified\index.js:351:5)
    at md2telegraphNodes (file:///C:/Users/gut/source/study/mydemo/src/util/md2teleph.js:10:14)
    at Object.convertMd2Ph (file:///C:/Users/gut/source/study/mydemo/src/service/md2ph.js:5:29)
    at file:///C:/Users/gut/source/study/mydemo/src/router/md.js:10:30
    at dispatch (C:\Users\gut\source\study\mydemo\node_modules\koa-compose\index.js:42:32)
    at C:\Users\gut\source\study\mydemo\node_modules\koa-body\index.js:148:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
My code is as follows
```
import remarkParse from 'remark-parse';
import remarkTelegraph from 'remark-telegraph';
import unified from 'unified';

async function md2telegraphNodes(markdown) {
    try {
        const vFile = await unified()
            .use(remarkParse)
            .use(remarkTelegraph)
            .process(markdown);

        const nodes = JSON.parse(vFile.contents);
        console.log('Create Page :', nodes);
        return nodes;
    } catch (err) {
        console.log(err);
    }
}

export default md2telegraphNodes;
```

My test input markdown string is as follows:
```
# h1 Heading 8-)
## h2 Heading
### h3 Heading
#### h4 Heading
##### h5 Heading
###### h6 Heading


## Horizontal Rules

___

---

***


## Typographic replacements

Enable typographer option to see result.

(c) (C) (r) (R) (tm) (TM) (p) (P) +-

test.. test... test..... test?..... test!....

!!!!!! ???? ,,  -- ---

"Smartypants, double quotes" and 'single quotes'
```

**Environment:**
 - Node.js version: 16.14.0
 - Operating System: windows 10

**Comment by pustovitDmytro** [comment]
Hi, sorry for the late response. I'm from Ukraine and don't have much time for a package now. 
Check and specify your remark versions: I tested the package with     
- "remark-parse": "9.0.0",
- "remark-telegraph": "1.0.4",
- "unified": "9.2.2"
You can check the usage example [here](https://github.com/pustovitDmytro/semantic-release-telegram/blob/master/src/telegram/Telegraph.js).  If you use newer versions (e.x unified v10 with ESM support), it could be breaking changes at API. please check unified [release notes](https://github.com/unifiedjs/unified/releases/tag/10.0.0) for upgrade details

**Comment by nanoia** [comment]
> Hi, sorry for the late response. I'm from Ukraine and don't have much time for a package now. Check and specify your remark versions: I tested the package with
> 
> * "remark-parse": "9.0.0",
> * "remark-telegraph": "1.0.4",
> * "unified": "9.2.2"
>   You can check the usage example [here](https://github.com/pustovitDmytro/semantic-release-telegram/blob/master/src/telegram/Telegraph.js).  If you use newer versions (e.x unified v10 with ESM support), it could be breaking changes at API. please check unified [release notes](https://github.com/unifiedjs/unified/releases/tag/10.0.0) for upgrade details

Thank you very much for your reply, and i sincerely wish you and your family to remain safe and healthy, and may peace come soon.
